### ISSUE TITLE
Reconsider the breaking changes made in version 0.16.0

### ISSUE THREAD

**Issue by lewoudar** [lundberg/respx#114]
Hi Lundberg,
I hope my thoughts will find an echo so here I go. For me `httpx` is the modern `requests` library and `respx` is the *alter ego* of [responses](https://pypi.org/project/responses/). Now if we compare the new syntax 
```python
respx.post("https://some.url/", status_code=200, content={"x": 1})
```
to the previous one

```python
respx.post("https://some.url/").mock(return_value=Response(200, json={"x": 1})
```
There are some disavantages that I see:
- You add boilerplate code for the user
- You force the users to think about the low level details of `httpx` instead of focusing on what they really want to test. 

The second point is the one that is frustrating me now. I bet my 2 cents that many users like me don't want to know how `httpx` constructs its http response but just need to think about the payload sent, the http status code and the response body. `respx` was perfect for that before this release.

The same issue also applied to this syntax `respx.post("https://some.url/").mock(side_effect=callback)`

I don't know if there are technical limitations that imposed this new style but if it is the case or you are convinced that the `mock` approach is the best way to do, please consider create wrappers (even if there are limited in some ways) to the old behaviour so that users who don't want to think about the low level details can still take pleasure to use your library.

Best regards

**Comment by lundberg** [comment]
Thanks for your feedback @lewoudar.

I totally agree that the old api was nice, but it had it's disadvantages, both in usage and limitations for future features.

The main goal with the change was to separate the arguments used for matching a request, from the arguments used for the response payload.

Why separate them? Well for two reasons...

First, to align with the `HTTPX` api, mentioned by the maintainers. I see it as..if you know httpx, then you *"know"* respx.

Secondly, version `0.16.0` opened up a lot of new options for *how* to match the request, for example `params` (suggested in #63) or request body (suggested in #83) etc. *(see [patterns](https://lundberg.github.io/respx/api/#patterns) api docs for a complete list)*

> I don't know if there are technical limitations that imposed this new style...

Consider you want to mock a response for a `POST` with certain content body sent with `HTTPX` like this:
```py
response = httpx.post("https://example.org/", content="foobar")
```
With the new api this is identical in RESPX, and would match a POST request to that url, with that given content.
```
route = respx.post("https://example.org/", content="foobar")
```
That wouldn't be possible with the old api since `content` arg was occupied by the payload response content.

About the separate response payload, I turned to the familiar unittest `Mock` api we all use and know, completing the change by mimicking two known api's.

> ...please consider create wrappers...

Since I also liked the simplicity with the old api, I sure *did* create wrappers ;-)

A super simple shortcut using `%`, like old-style formatting a string, *(see [docs](https://lundberg.github.io/respx/guide/#modulo-shortcut))*
```py
respx.get("https://example.org/") % 204
# or
respx.get("https://example.org/") % dict(json={"foo": "bar"}
```

if you don't like the modulo style syntax, there is also the [respond](https://lundberg.github.io/respx/api/#respond) method, wrapping `.mock(...)`.
```py
respx.get("https://example.org/").respond(204)
```

Hope that helped.

**Comment by lundberg** [comment]
Updated the [upgrade docs](https://lundberg.github.io/respx/upgrade/) with `respond` and `modulo` shortcut examples.

**Comment by lewoudar** [comment]
Hi @lundberg ,
Aww that is great! To be honest, I didn't read the whole new documentation, just the first page and the upgrade page.
After seeing the new doc, it seems `respx` is more powerful than ever. What I usually do to validate payload using `responses` is the use of **callbacks**.
With the new features of respx, I don't think it is still necessary to use this pattern. Thank you for the clarification!

Have a nice day :)

**Comment by lundberg** [comment]
This kind of feedback is really helpful @lewoudar, thanks.

It shows that the documentation/examples needs even more attention to detail. The upgrade docs should've been clearer, but I naively thought the full docs were enough ;-)

Please tell if you think anything else should be added to the upgrade page, or the user guide of course.
