### ISSUE TITLE
Mocking optional parameters is dependant on registration order

### ISSUE THREAD

**Issue by inkychris** [lundberg/respx#129]
When mocking responses with optional parameters, the mock for the case when a parameter is not provided currently has to be registered last, otherwise mocks with specific parameter values are ignored:
```python
import httpx
import respx


responder = respx.mock(assert_all_called=False, base_url='https://test.org/')

responder.get(url='test').respond(content='no key param')
responder.get(url='test', params={'key': 'value1'}).respond(content='value1')
responder.get(url='test', params={'key': 'value2'}).respond(content='value2')

with responder:
    client = httpx.Client(base_url='https://test.org/')
    for param_value in (None, 'value1', 'value2'):
        content = client.get('test', params={'key': param_value}).content
        print(f'{param_value}: {content.decode("utf-8")}')
```
## Current output:
```
None: no key param
value1: no key param
value2: no key param
```
## Expected output:
Achievable by reordering the mock definitions:
```python
...
responder.get(url='test', params={'key': 'value1'}).respond(content='value1')
responder.get(url='test', params={'key': 'value2'}).respond(content='value2')
responder.get(url='test').respond(content='no key param')
...
```
```
None: no key param
value1: value1
value2: value2
```

**Comment by lundberg** [comment]
Thanks for your input. The docs might not be clear enough on this one.

What you're describing is true, the mocked responses, e.g. `routes`, are matched and mocked in added order.

This is by design and means that more specific URLs (patterns) needs to be mocked earlier than the once with less _"details"_, when they share parts of the patterns, i.e. leading URL.

See it as how any web server or URL router works, first match will return the response.

However, auto sorting of the routes might be possible. I've actually tried to implement this feature using dynamic scoring of each given pattern of a `route`. But it's a hard one and could give unwanted behaviour and results even harder to understand. 

The sorting key/score may also differ in opinion per RESPX user, i.e. should a cookie rank a route higher than a similar with a param, or headers vs body etc?

But I've not given up the idea, and if I manage to get a reliable and conceivable auto sorting feature working, it'll definitely be an *opt-in* setting of the RESPX router, leaving the current _match-in-added-order_ the default behaviour, since it's kind of standard and most straight forward IMO.

**Comment by StephenBrown2** [comment]
I think it's generally expected that the mock that most closely matches the request is the one that should respond, but that leaves the "more specific" interpretation up to the library, rather than the user. I think that the following sentence should definitely go in the docs, as it makes much sense:
> This is by design and means that more specific URLs (patterns) needs to be mocked earlier than the once with less "details", when they share parts of the patterns, i.e. leading URL.

**Comment by lundberg** [comment]
Agree @StephenBrown2, we should add a section in the docs describing this.

I naively thought that users expected the _"added order"_ behaviour, since `responses` and `requests-mock` works like this for the `requests` lib, and also servers like `django`, `nginx` etc also matches on added/given order. My bad, never assume 
that things are expected 😉

That said, I'd be a really nice feature to support auto sorted routes and enable this, but...

...what does _"most closely matched"_ really mean, and what is actually expected?

I'll try to describe the challenge....

As the docs explains, RESPX uses pattern matching to "catch" and mock a request. This means that _"under the hood"_ a URL like `https://example.org/foo/` is turned into individual [patterns](https://lundberg.github.io/respx/api/#patterns), i.e. `scheme`, `host`, etc.

Sorting the routes reversed by a URL string is easy, and would enable a most closely matched route, i.e. test longer urls first. So, we know that more patterns could give us a hint that it is probably a better match, i.e. path + params ranks higher than a route with only path, right? But is that always true?

The challenge is when we compare patterns like `params`, `headers`, `json` (body), `cookies` etc. If two routes has the same host and path, but one route has a given param and the other route has a header, which one is expected to mock a request that has both that param and header?

What is expected here?
```py
respx.get("https://example.org/", params={"foo": "bar"}).respond(200)
respx.get("https://example.org/", headers={"ham": "spam"}).respond(404)

response = httpx.get("https://example.org/", params={"foo": "bar"}, headers={"ham": "spam"})
assert response.status_code == ???
```

To make it even harder, we have the RESPX [lookups](https://lundberg.github.io/respx/api/#lookups) and [operators](https://lundberg.github.io/respx/api/#operators) 😅. These must also affect the sort _"weight"_...narrower lookup yields better match than wider, i.e. `__exact` over `__contains` etc. Same goes for the operators (which can be nested), probably test outer `AND`'ed patterns before `OR`'ed etc.

What is expected here? (maybe easier to argue about, but still)
```py
respx.route(method__in=["GET", "POST"], path__startswith="/api/").respond(200)
respx.route(method="GET", path="/api/foo/").respond(404)

response = httpx.get("https://example.org/api/foo/")
assert response.status_code == ???
```

...or what is expected here? is the route with a given method expected or the other with more patterns/details?
```py
respx.route(scheme="https", host="example.org", path="/api/foo/", json={"foo": "bar"}).respond(200)
respx.route(method="POST", host="example.org", path="/api/foo/").respond(201)

response = httpx.post("https://example.org/api/foo/", json={"foo": "bar"})
assert response.status_code == ???
```

I know that these examples might be weird and maybe not real cases, but for a sorting key to be calculated it has to be taken into account to make it predictable and consistent. It also makes the code/behaviour non-hard-coded and allows easier adding of more patterns and lookups later.

It all boils down to giving pattern types different scores, take user given pattern values length/weight into account, score lookups and operators, and then finally combine everything and end up in a total score for each route to sort on. Then (fingers crossed) the first matching route (top-down) should give you the mostly matched one 😅.

Like I said, I've tried this and got it 90% working and still think it's possible. Scoring and stuff still needs to be argued about even when the logic works and are in place. Users might have different opinions of what matches more closely than what other users expect.

**Comment by StephenBrown2** [comment]
Very well laid out. All I have to say about developer vs user expectations is: https://youtu.be/4JjrYm03Al4 😂😄😅

**Comment by inkychris** [comment]
It's certainly a lot more complicated than I'd appreciated when I created this issue! 

Personally, I'd expect the following results from the examples you gave:
1. The user has not adequately mocked behaviour so a "a not mocked" exception should be raised because the two mocks provided are hierarchically equivalent. There's no way for respx to decide which to use so it shouldn't try.
2. Status code should be `404`. Both the method and the path are more specific.
3. Status code should be `200`. The content is more specific, which is the only distinction between the routes since the first implicitly includes "POST" and the second implicitly includes "https" scheme.

Certainly for the content itself, I think the implicit acceptance of parameters/headers/body being omitted still matching a mock may be complicating the situation?

**Comment by lundberg** [comment]
I agree @inkychris on all except that I think nr 1 could be argued to also be solvable by a hard decision that i.e. params is more specific than headers, but then we'll end up in a rabbit hole of whats right and wrong 😉. Maybe a warning is enough?

Also, as long as the documentation is clear on how it's working, I guess anything is OK, and that the edge cases could be considered bad or misused user behaviour?

> Certainly for the content itself, I think the implicit acceptance of parameters/headers/body being omitted still matching a mock may be complicating the situation?

Yes, thats the thing. I'd like the "algorithm" to not know if it is a scheme, param or body, and not take actions on it, just automatically score everything up, resulting in a "correct" test/match order.

**Comment by lundberg** [comment]
It was a few months since I tried this, but I'll try to rebase and push the branch so we actually have code to discuss about.

**Comment by StephenBrown2** [comment]
Personally I think a doc update is good enough... but discussing code is also good.

**Comment by lundberg** [comment]
This is now [explained](https://lundberg.github.io/respx/guide/#routing-requests) in the docs.
