### ISSUE TITLE
Test for retries does not result in expected call_count

### ISSUE THREAD

**Issue by rmporsch** [lundberg/respx#141]
I am actually not sure this issue should be posted on respx or httpx.
I am trying to upgrade our httpx version. Previously we had some custom retry functionality build in, since the new changes in httpx this seems not necessary anymore. However, currently this test below fails. I am trying to understand why.

```
 @respx.mock
 async def test_connection_error(self):
      mock = respx.post("https://example.org/").mock(side_effect=httpx.ConnectError, return_value=httpx.Response(503))
      with pytest.raises(httpx.ConnectError):
          async with httpx.AsyncClient(transport=httpx.AsyncHTTPTransport(retries=3)) as c:
              await c.post("https://example.org/", json={})
      assert mock.call_count == 3 #  actually get 1
  ```

**Comment by lundberg** [comment]
Your test case is using the `httpx.AsyncHTTPTransport` which is httpx `master` and not yet released.

I have the PR #142 that deals with some of the new httpx transport api. Could be worth a try to test with that RESPX commit to rule out any other upcoming release changes of httpx and respx. Not sure if it does matter though in this case.

One thing that could affect the retry might be the type of exception, could you try `side_effect=httpcore.ConnectError` and see if that triggers the httpx retry mechanism?

FYI: `side_effect` has precedence over `return_value`, so you don't need to pass `return_value` in your case, since it will not be used.

**Comment by rmporsch** [comment]
Thanks a lot for the reply! And also just to say this is an excellent library! 

I used the most recent httpx version from pypi and since I found the retries in the documentation I assumed it was implemented (see [here](https://www.python-httpx.org/async/#explicit-transport-instances))

I actually previously also tried `side_effect=httpcore.ConnectError` but without much success.

Will close this issue for now then. Thanks a lot for the reply.

**Comment by deven96** [comment]
This was never fixed as I still have issues testing retries with respx

**Comment by deven96** [comment]
Is there a way I could work this in myself? @lundberg

**Comment by lundberg** [comment]
Specifying `retries` on a httpx transport, like `httpx.AsyncHTTPTransport(retries=3)`, _only_ configures the client to perform 3 socket _connection_ attempts, as can be read [here](https://www.python-httpx.org/advanced/#usage_1) in the httpx docs.

The actual HTTP request is only sent by the client once a connection is established.

This is why you only see 1 call in respx, i.e. one request attempt, but three connection attempts in your test/example.

If you're looking for request retries, e.g. retrying the request on a specific response HTTP status, I think you need to implement the client retry mechanism yourself. This could then be mocked with respx using an [iterable side effect](https://lundberg.github.io/respx/guide/#iterable).
