### ISSUE TITLE
Support HTTPX params argument

### ISSUE THREAD

**Issue by symroe** [lundberg/respx#63]
I'm using `httpx` in the following way:

```
kwargs = {"limit": 20, "offset": 20}
httpx.get(url, params=kwargs)
```

This means that `httpx` is formatting the GET params for me.

When I come to mock this call, it would be great to be able to do:

```
respx.get(url, status_code=200, params=kwargs)
```

This would allow me to use the same logic for creating (and changing) the params, rather than hard coding them.

**Comment by lundberg** [comment]
Great suggestion, will add this feature after vacation, if you're not up to a PR ;-)

**Comment by symroe** [comment]
Happy to work on a PR, or at least try :)


Just having a look. My first idea was to use `httpx` to build the params up (or maybe, the whole URL or request), but I've seen the TODO commends about dropping the usage. Can you explain this a little? It makes sense to me to piggyback on `httpx` as much as possible, so I expect I'm missing something!

Without using `httpx`, I expect it's best to take their concept: take the argument but also merge the params when building a URL.

This would allow for using the params with a URL that already contains them, e.g:

`respx.get("https://example.com?page=2", status_code=200, params={"foo": "bar"})`

would translate in to the URL `https://example.com?page=2&foo=bar`.

Does that seem reasonable to you?

**Comment by lundberg** [comment]
Worked on this a little bit yesterday but got stuck on the url merging and matching.

> Can you explain this a little? It makes sense to me to piggyback on httpx as much as possible, so I expect I'm missing something!

I used httpx models like URL and others in early respx versions, but since httpx is changing so rapidly internally, eg models, apis, args etc, it helped a lot to just mock without relying on httpx structures. Most of the times respx stopped working was due to httpx internal changes that didn't really affect respx.

Now that httpx has more stable apis and only exposes some of the models "public", it might be smart to start leaning on some of the models like URL to not re-implement those parts.

Other than that, respx actually mocks httpcore and not httpx, so maybe nicest would be to not rely at all on httpx, so that future libs that uses httpcore can use respx without the httpx dependency. But this is not a dealbreaker for relying on httpx IMO.
