### ISSUE TITLE
Big overhead when mocking 149 urls

### ISSUE THREAD

**Issue by konstin** [lundberg/respx#90]
I'm currently migrating from aiohttp/aioresponses to httpx/respx, and seeing a large regression in test times. An integration test where I mock 149 urls which took 0.5s with aioresponses now takes 2.2s with respx. `build_request` seems to be the major culprit. I've created a flamegraph with py-spy ([full svg as gist](https://gist.github.com/konstin/f4e17d5c77ebc0b13f4e6f1a7bb27737)):

![grafik](https://user-images.githubusercontent.com/6826232/95573627-072a8d00-0a2c-11eb-85a1-66f017cfbe1a.png)

Test code

```python
@pytest.mark.asyncio
async def test_integration_json():
    with respx.mock(
        assert_all_mocked=True,
        assert_all_called=True,
    ) as respx_mock:
        for file in Path("test-data/snapshots").iterdir(): # Directory with 149 files
            respx_mock.get(
                "https://www.example.com/" + file.name.replace(".html", ""),
                content=file.read_text(),
                content_type="text/html",
            )

        # Actual test logic
```

**Comment by lundberg** [comment]
This is really useful findings!

You're mentioning `build_request`, which has been refactored/renamed to `decode_request` in master. There are no big changes though, we still rely on creating a httpx.Request which in the flamegraph looks to be the major thing, i.e. not respx related code.

It would be interesting to see if the flamegraph looks different with respx master and latest httpx.

**Comment by konstin** [comment]
[pretty similar](https://gist.github.com/konstin/5ca91c398c5252ada7d0e7ec13e3575d)

![grafik](https://user-images.githubusercontent.com/6826232/95578328-03026d80-0a34-11eb-8aa1-a9a32e25b335.png)

**Comment by lundberg** [comment]
Yep, thats pretty much the same ;-)

It's interesting that `decode_request` is visible but not `decode_response` which is also called for each matched/mocked response. I guess `httpx.Request` is more expensive to instantiate than the `httpx.Response`.

Not sure what we can do at this moment. Caching objects for reuse in probably not an option since the request content could be a stream that we can't/shouldn't exhaust, meaning its hard to build a hash cache key. And even if possible, it's probably not being sent lots of same requests anyways.

FYI, respx works with the `httpcore` transports to match requests and mock responses at a lower level, for two reasons; one is to not depend on the httpx internals for easier maintainability and automatic support for future httpx client features, and secondly to allow mocking responses for other future libs using `httpcore`.

This is why the `encode_request` is used to instantiate a `httpx.Request` for the calls statistics. While typing this, I'm thinking we could do that lazy, meaning we actually only need to instantiate the Request on `respx.calls` usage in a test assertion. Would that be an option and solution to this maybe?

**Comment by lundberg** [comment]
Could you clone respx and add a `return` as the first line in [transport.record](https://github.com/lundberg/respx/blob/master/respx/transports.py#L272) and re-run the test to see how much of the flamegraph is affected by not instantiating the `httpx.Request` when recording stats.

About the matching-side, I looked at the code and we could easily move the instatiation of `httpx.Request` there to be done only when needed, i.e. when using callbacks.

**Comment by lundberg** [comment]
Also, please try #91 that enhances request usage in callbacks.

**Comment by konstin** [comment]
With master:

```
Benchmark #1: pytest tests/test_z_integration.py
  Time (mean ± σ):      2.740 s ±  0.024 s    [User: 2.806 s, System: 0.132 s]
  Range (min … max):    2.696 s …  2.776 s    10 runs
```

With `return`:

```
Benchmark #1: pytest tests/test_z_integration.py
  Time (mean ± σ):      2.695 s ±  0.060 s    [User: 2.775 s, System: 0.114 s]
  Range (min … max):    2.630 s …  2.831 s    10 runs
```

![grafik](https://user-images.githubusercontent.com/6826232/95663399-4695ce00-0b3f-11eb-8a05-14dc1d6cee3c.png)

With #91:

```
Benchmark #1: pytest tests/test_z_integration.py
  Time (mean ± σ):     823.4 ms ±  29.0 ms    [User: 917.9 ms, System: 105.8 ms]
  Range (min … max):   795.9 ms … 884.9 ms    10 runs
```

That one looks much better already!

![grafik](https://user-images.githubusercontent.com/6826232/95663499-fbc88600-0b3f-11eb-9d35-b5888e653c3d.png)

**Comment by konstin** [comment]
With #92:

```
Benchmark #1: pytest tests/test_z_integration.py
  Time (mean ± σ):      2.740 s ±  0.064 s    [User: 2.819 s, System: 0.118 s]
  Range (min … max):    2.624 s …  2.834 s    10 runs
```

![grafik](https://user-images.githubusercontent.com/6826232/95663572-92954280-0b40-11eb-978f-1059cb436e9e.png)

**Comment by lundberg** [comment]
Super!

Will merge both PR's soon.

**Comment by lundberg** [comment]
Re-opening this issue until #92 is merged @konstin

**Comment by lundberg** [comment]
RESPX `0.14.0` now released with the fixes for this issue, among others, @konstin.

Thanks @SlavaSkvortsov for helping closing this issue.
